### ISSUE TITLE
How to run this repo?

### ISSUE THREAD

**Issue by yugaljain1999** [GerjanVlot/BERT-ML.NET#4]
@gerjanvl @GerjanVlot After downloading pretrained model to desired location , what command should I follow to run local server on ASP.NET?
Thanks

**Comment by gerjanvl** [comment]
You need to have dotnet installed and pasted the model in the model folder.

Then go in the webapi folder.
run 'dotnet restore'
after that 'dotnet run'

**Comment by yugaljain1999** [comment]
@gerjanvl After following your steps as per here..
![image](https://user-images.githubusercontent.com/32617984/110962624-2df04500-8377-11eb-8700-ed24cf13bb5d.png)


 But I am getting this error on localhost..
![image](https://user-images.githubusercontent.com/32617984/110962440-026d5a80-8377-11eb-8fe2-b17d4fbde248.png)

What should I do to solve this?
Thanks

**Comment by Gigabyte0x1337** [comment]
https://technology.amis.nl/data-analytics/jupyter-notebook-for-retrieving-json-data-from-rest-apis/ does this help?

**Comment by Gigabyte0x1337** [comment]
The issue is everything is running in the notebook so not on your pc so you can't reach it. So you need to do a http request in your notebook with python or javascript.

**Comment by yugaljain1999** [comment]
@GerjanVlot how can I do http request in notebook with python or javascript?
Can you please list down steps to do that?
Thanks

**Comment by yugaljain1999** [comment]
@GerjanVlot @gerjanvl It showing get requests on command line when I tried on local pc 
![image](https://user-images.githubusercontent.com/32617984/110972675-431ea100-8382-11eb-9d3e-5d5fc01986fb.png)


but still on browser it isn't showing anything as follows..
![image](https://user-images.githubusercontent.com/32617984/110972584-26826900-8382-11eb-9ef4-584b36059d66.png)
What should I do now? Please help...

**Comment by yugaljain1999** [comment]
@gerjanvl I am using .NET SDK 3.1.403 .. Is it compatible version to work with this repo?
Please reply
thanks

**Comment by yugaljain1999** [comment]
Issue is resolved
