### ISSUE TITLE
How to run just C# wrapper instead of whole webserver api?

### ISSUE THREAD

**Issue by yugaljain1999** [GerjanVlot/BERT-ML.NET#5]
@gerjanvl @justinormont @GerjanVlot I want to run just C# wrapper using dll files because system only accepts c# wrapper and we can't run localserver in our system..
So how can I run just C# script to predict answers from given question without using web apis?
Please help me in this..
Thanks

**Comment by Gigabyte0x1337** [comment]
Added a console app, let me know if this helps.

**Comment by yugaljain1999** [comment]
@GerjanVlot Thanks, Can you please tell me commands to run this console app?

**Comment by yugaljain1999** [comment]
@GerjanVlot I am facing this error while running `dotnet run` command to run this code in console..
`Program.cs(5,1): error CS8652: The feature 'top-level statements' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. [C:\Users\HP\BERT-ML.NET\BERT.Console\BERT.Console.csproj]

The build failed. Fix the build errors and run again.`

Please help me to solve this as it's important for me to do so..
Thanks

**Comment by Gigabyte0x1337** [comment]
dotnet run -- "Bob is walking through the woods collecting blueberries and strawberries to make a pie." "What is his name?". I updated te git repo without top-level statements

**Comment by yugaljain1999** [comment]
@GerjanVlot I am still getting same error after running this command..
What should I do?
Thanks

**Comment by Gigabyte0x1337** [comment]
Do a git clone again

**Comment by yugaljain1999** [comment]
@GerjanVlot Thanks, it's working now..
One last query - Why you didn't use libtorch to compile torch functions instead of ML.NET?

**Comment by Gigabyte0x1337** [comment]
Onnx is an execution runtime for end user applications not for training or experimentation.  https://onnx.ai/

**Comment by yugaljain1999** [comment]
Ok, so that's why you used ML.NET to handle onnx .
Thanks
