### ISSUE TITLE
How to load the model and vocabulary from a SQL Server database?

### ISSUE THREAD

**Issue by ZedZipDev** [GerjanVlot/BERT-ML.NET#6]
In the current implementation we load the model from a file: bertsquad-10.onnx
By some reasons I'd like to upload this file to a database (SQL Server) and load it from the database.
Is it possible to do it?
For example, I want to move your code to SQLCLR function. It is impossible to work with file in a common case.
And the best way is to load vocabulary and model from a database.

**Comment by Gigabyte0x1337** [comment]
You can add them as resource files in you project maybe or load them from a specific table in your SQLCLR function.
I don't know what you are trying to do but i think it's easier to just query the database and process it in console app or a background job.

This is a bit out of scope, ask it on stackoverflow if mentioned above doesn't work.
